config/routes.rb
Rails.application.routes.draw do
  
  namespace :api, defaults: {format: 'json'}  do
    namespace :v1 do
      
      resources :schools
      
    end
  end  
  
  
  devise_for :users
  
  resources :subjects do
    collection do
      get 'grades_list'
    end
    member do
     
    end  
  end
  
  
  match 'home/*path' => 'home#index', via: [:get, :post, :put, :patch, :delete]

  resources :schools 
  
#  get 'students/index'
#  get 'students/new'
#  post 'students/create'

#  OR

   resources :students, only: [:index, :new, :create] do
    resources :profile
   end
  
  root to: "schools#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sample.rb
class Sample < ApplicationRecord

  validates :name, presence: true, uniqueness: true


  def set_name(str)
    self.name = str
  end


end

app/models/school.rb
class School < ApplicationRecord
  validates :is_active, acceptance: { message: 'must be true' }
#  validates :name, exclusion: { in: %w(kishore venkat), message: "%{value} is reserved." }
#  validates :name, inclusion: { in: %w(kishore venkat), message: "%{value} is not in the included list." }
#  validates :name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }

#    validates :started_on, numericality: true

#   validates :name, uniqueness: true
#    validates :name, uniqueness: { scope: :started_on, message: "should happen once per year" }
      validates :name, uniqueness: { case_sensitive: false }


  def set_name(str)
    self.name = str
  end

end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API

end

app/controllers/api/v1/schools_controller.rb
class Api::V1::SchoolsController < Api::V1::BaseController

  def index
    schools = School.all
    render json: {status: "ok", schools: schools.as_json}.to_json, status: 200
  end
  
  def create
    school = School.new(school_params)
    if school.save
      render json: {status: "ok", message: "created!"}.to_json, status: 200
    else
      render json: {status: "error", message: school.errors.full_messages.first}.to_json, status: 500
    end
  end
  
  private
  def school_params
    params.permit(:name, :address, :started_on)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index]
  
  
  def after_sign_in_path_for(resource)
    if user_signed_in?
      subjects_path
    else
      new_user_session_path
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ReverseProxy::Controller

  def welcome
    
  end

  def index
    raise "h"
    # Assuming the WordPress server is being hosted on port 8080
    reverse_proxy "http://localhost:3005/", path: params[:path] do |config|
      
      config.on_response do |code, response|
        Rails.logger.debug "\n\n..RESPONSE....#{code}..#{response.body.inspect}...\n"
      end   

      config.on_error do |code, response|
        Rails.logger.debug "\n\n..ERROR...#{code}..#{response.body.inspect}...\n"
      end   

      config.on_complete do |code, response|
        Rails.logger.debug "\n\n..COMPLETE...#{code}..#{response.body.inspect}...\n"
      end  

      config.on_success do |code, response|
        Rails.logger.debug "\n\n..SUCCESS...#{code}..#{response.body.inspect}...\n"
      end    
     
      # We got a 404!
      config.on_missing do |code, response|
        Rails.logger.debug "\n\n.MISSING...#{code}..#{response.body.inspect}...\n"
        #raise "h"
        #redirect_to root_url and return
      end
      
      # There's also other callbacks:
      # - on_set_cookies
      # - on_connect
      # - on_response
      # - on_set_cookies
      # - on_success
      # - on_redirect
      # - on_missing
      # - on_error
      # - on_complete
    end
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  
  #http_basic_authenticate_with name: "karthik", password: "123456"
  before_action :load_school, only: [:edit, :update, :show, :destroy]

  layout 'new_layout', except: [:index, :new]
  
  def index
    @schools = School.all
    respond_to do |format|
      format.html {  } #redirect_to root_url, alert: "You're stuck here!" }
      format.js   { render layout: false }
      format.xml  { render xml: @schools }
      format.json { render json: @schools }
    end
  end
  
  def new
    @school = School.new
#    send_file("#{Rails.root}/README.md",
#              filename: "README.md",
#              type: "text/markdown")
  end
  
  def create
    @school = School.new(school_params)
    if @school.save
      UserMailer.welcome_email("karthik.mchi@gmail.com").deliver_now
      redirect_to schools_path, notice: "Success!"
    else
      render action: "new"
    end
  end
  
  def edit
  end
  
  def update
    if @school.update(school_params)
      redirect_to schools_path, notice: "Updated!"
    else
      render action: "edit"
    end
  end
  
  def show
    render layout: "other_layout"
  end
  
  def destroy
    @school.destroy
    redirect_to schools_path, notice: "Removed!"
  end

  
 private
  def load_school
    Rails.logger.debug "\n...I'm in.\n"
    @school = School.find(params[:id])
  end 
  
   def school_params
    params.require(:school).permit(:name, :address)
  end 

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def grades_list
    @subjects = Subject.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :grade, :teacher)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/home/index.html.erb
index

app/views/home/welcome.html.erb
Hello

<%= form_tag "/schools", method: "GET" do %>
  <div>
    <%= text_field_tag "path[service_id]" %>
    <br><%= text_field_tag "path[url]" %>
    <br><%= text_field_tag "path[method]" %>
    <br><%= text_field_tag "path[action_name]" %>
    <br><%= text_field_tag "path[controller_name]" %>
    <br><%= text_area_tag "path[area]", '', rows: "2", cols: "40" %>
    <br><%= number_field_tag "path[number]" %>
    <br><%= number_field_tag "path[number]", nil, step: 0.5 %>
    <br><%= select_tag "path[drop]", options_for_select([["one", 1], ["two", 2]]) %>
    <br><%= radio_button_tag "path[gender]", "male" %>Male
    <br>
    <%= radio_button_tag "path[gender]", "female" %>Female
    <br>
    <%= check_box_tag "path[check]", true %> Accept terms
    <br>
    <%= hidden_field_tag "path[hide]", '', value: "karthik" %>
  </div>
  <%= submit_tag "SAVE" %>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
      <% if user_signed_in? %>
        <li>
        <%= link_to('Edit registration', edit_user_registration_path) %>
        </li>
        <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
        </li>
      <% else %>
        <li>
        <%= link_to('Login', new_user_session_path)  %>  
        </li>
        <li>
          <%= link_to('Register', new_user_registration_path)  %>
        </li>
      <% end %>
      </ul>
    </header>
  
  
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>
  </body>
</html>

app/views/layouts/new_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Karthik</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div style="width:100%">
      <div style="width:20%;float:left;background:blue;">
        Sidebar
      </div>      
      <div style="width:80%;float:left;background:#efefef">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: name %>
          <% end -%>
          <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/layouts/other_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Karthik</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div style="width:100%">
      <div style="width:40%;float:left;background:green;">
        Sidebar
      </div>      
      <div style="width:60%;float:left;background:#efefef">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: name %>
          <% end -%>
          <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/schools/_form.html.erb
<%= form_for @school do |f| %>
  
  <% if @school.errors.any? %>
    <p><%= @school.errors.full_messages.join(", ") %></p>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>  

  <div>
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>  
  
  <%= f.submit "SAVE" %>
  
<% end %>

app/views/schools/edit.html.erb
<h3>EDIT School</h3>

<%= render "form" %>

app/views/schools/index.html.erb
<h3>Schools</h3>

<table>
<thead>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th></th>
  </tr>
</thead>
<tbody>
  <% @schools.each do |school| %>
    <tr>
      <td><%= school.name %></td>
      <td><%= school.address %></td>
      <td>
        <%= link_to "Edit", edit_school_path(school) %>
        <%= link_to "Show", school_path(school) %>
        <%= link_to "Remove", school_path(school), method: :delete, confirm: "Are you sure?" %>
      </td>
    </tr>
  <% end %>
</tbody>
</table>


<%= link_to "New School", new_school_path %>

app/views/schools/new.html.erb
<h3>New School</h3>

<%= render "form" %>

app/views/schools/show.html.erb
Show
<br>
Name: <%= @school.name %><br>
Address: <%= @school.address %>

<br>

<%= link_to "Back", schools_path %>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>

app/views/students/new.html.erb
<h1>Students#new</h1>
<p>Find me in app/views/students/new.html.erb</p>

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :grade %>
    <%= form.text_field :grade %>
  </div>

  <div class="field">
    <%= form.label :teacher %>
    <%= form.text_field :teacher %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/grades_list.html.erb
Grades List

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Grade</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.grade %></td>
        <td><%= subject.teacher %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>
<br>
<%= link_to 'Grades list', grades_list_subjects_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @subject.grade %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @subject.teacher %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>